# Copyright 2022 Michael Turner
# adapted from
# https://github.com/manna-harbour/miryoku
# note: configuration below sets "qwerty" on the assumption that proper
#       dvorak mapping will be handled in the OS

name: 'corne-ish_zen v2 modified miryoku'
on: workflow_dispatch
jobs:
  build:
    uses: ./.github/workflows/main.yml
    secrets: inherit
    with:
      board: '["corneish_zen_v2_left","corneish_zen_v2_right"]'
      alphas: '["QWERTY"]'
      nav: '["invertedT"]'
      custom_config: '["#define MIRYOKU_KLUDGE_MOUSEKEYSPR"]'
      kconfig: '["CONFIG_ZMK_MOUSE=y\nCONFIG_ZMK_DISPLAY_HIDE_MOMENTARY_LAYERS=y\nCONFIG_CUSTOM_WIDGET_LOGO_IMAGE_MIRYOKU=y\nCONFIG_IL0323_INVERT=y"]'
      branches: '["manna-harbour/zmk/zen zmkfirmware/zmk/main ftc/zmk/mouse-ftc"]'
